apiVersion: v1
kind: Service
metadata:
  name: plants-app-service
spec:
  selector:
    app: plants-app
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plants-app-deployment
  labels:
    app: plants-app-deployment
spec:
  selector:
    matchLabels:
      app: plants-app
  template:
    metadata:
      labels:
        app: plants-app
    spec:
      containers:
      - name: plants-app
        image: plants-app
        resources:
          limits:
            cpu: "1.0"
            memory: "1Gi"
        ports:
        - containerPort: 8080
